module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    HOSTEL_MANAGER: "HOSTEL_MANAGER",
  },
  USER_TYPE: {
    SERVICE_CLIENT: "SERVICE_CLIENT",
    SERVICE_PROVIDER: "SERVICE_PROVIDER",
  },
  ROLE: {
    USER: "USER",
  },
  ACCOUNT_TYPE: {
    FACEBOOK_ACCOUNT: "FACEBOOK_ACCOUNT",
    GOOGLE_ACCOUNT: "GOOGLE_ACCOUNT",
    VENT_ACCOUNT: "VENT_ACCOUNT",
  },
  ORDER_STATUS: {
    COMPLETED: "COMPLETED",
    BOOKED: "BOOKED",
    IN_PROGRESS: "IN_PROGRESS",
  },
};
