module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    HOSTEL_MANAGER: "HOSTEL_MANAGER",
  },
  USER_TYPE: {
    SERVICE_CLIENT: "SERVICE_CLIENT",
    SERVICE_PROVIDER: "SERVICE_PROVIDER",
  },
  ROLE: {
    USER: "USER",
  },
  ACCOUNT_TYPE: {
    FACEBOOK_ACCOUNT: "FACEBOOK_ACCOUNT",
    GOOGLE_ACCOUNT: "GOOGLE_ACCOUNT",
    VENT_ACCOUNT: "VENT_ACCOUNT",
  },
  SERVICE_TYPE: {
    ONLINE: "ONLINE",
    REQUESTING: "REQUESTING",
    BOOKING: "BOOKING",
  },
  CURRENCY: {
    NGN: "NGN",
    USD: "USD",
  },
  CATEGORY_TYPE: {
    ONLINE: "ONLINE",
    REQUESTING: "REQUESTING",
    BOOKING: "BOOKING",
  },
  ORDER_STATUS: {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    PAID: "PAID",
    CANCELLED: "CANCELLED",
    STARTED: "STARTED",
    COMPLETED: "COMPLETED",
  },
  TRANSACTION_TYPE: {
    CREDIT: "CREDIT",
    DEBIT: "DEBIT",
    WITHDRAWAL: "WITHDRAWAL",
  },
  NOTIFICATION_TYPE: {
    MESSAGES: "MESSAGES",
    SERVICE_REQUEST: "SERVICE_REQUEST",
    FOLLOW_REQUEST: "FOLLOW_REQUEST",
    UNFOLLOW_REQUEST: "UNFOLLOW_REQUEST",
    ACCEPT_SERVICE_REQUEST: "ACCEPT_SERVICE_REQUEST",
    PAYMENT: "PAYMENT",
    OTHERS: "OTHERS",
    SERVICE_REQUEST_REJECTED: "SERVICE_REQUEST_REJECTED",
    REFERRAL_EARNED: "REFERRAL_EARNED",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
  },
  ACCEPTED_MESSAGE: "Please login and proceed to payment",
  REJECTED_MESSAGE: "Please login and look for other providers on the platform",
  ACCEPTED_STATUS: "has been accepted",
  REJECTED_STATUS: "was rejected by the provider",
  CANCELLED_STATUS: "has been cancelled by the client",
  CANCELLED_MESSAGE: "Please be on the out look for other Order from client",
};
